### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jetbrains/android/run/AvdComboBox

### ISSUE THREAD

**Issue by mikeliucc** [defrac/defrac-plugin-intellij#25]
Hi,

I'm using latest version of IntelliJ EAP (Preview 16).  When creating a test, the following error occurred.  The test profile did not create.  Please kindly look into this.

```
org/jetbrains/android/run/AvdComboBox
java.lang.NoClassDefFoundError: org/jetbrains/android/run/AvdComboBox
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:261)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:257)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:226)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:119)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:73)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:62)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at defrac.intellij.run.ui.DefracRunConfigurationEditor.createUIComponents(DefracRunConfigurationEditor.java:113)
    at defrac.intellij.run.ui.DefracRunConfigurationEditor.$$$setupUI$$$(DefracRunConfigurationEditor.java)
    at defrac.intellij.run.ui.DefracRunConfigurationEditor.<init>(DefracRunConfigurationEditor.java:60)
    at defrac.intellij.run.DefracRunConfiguration.getConfigurationEditor(DefracRunConfiguration.java:199)
    at com.intellij.execution.impl.ConfigurationSettingsEditor.<init>(ConfigurationSettingsEditor.java:220)
    at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.<init>(ConfigurationSettingsEditorWrapper.java:67)
    at com.intellij.execution.impl.SingleConfigurationConfigurable.<init>(SingleConfigurationConfigurable.java:65)
    at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:99)
    at com.intellij.execution.impl.RunConfigurable.a(RunConfigurable.java:1090)
    at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.java:1123)
    at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$2.consume(RunConfigurable.java:1161)
    at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$2.consume(RunConfigurable.java:1158)
    at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:82)
    at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:48)
    at com.intellij.ui.popup.list.ListPopupImpl.a(ListPopupImpl.java:386)
    at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:346)
    at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:476)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:542)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
    at java.awt.Dialog.show(Dialog.java:1084)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:792)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
    at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1661)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1610)
    at com.intellij.openapi.options.ex.SingleConfigurableEditor.access$001(SingleConfigurableEditor.java:45)
    at com.intellij.openapi.options.ex.SingleConfigurableEditor$1.run(SingleConfigurableEditor.java:130)
    at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:31)
    at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
    at com.intellij.openapi.options.ex.SingleConfigurableEditor.show(SingleConfigurableEditor.java:127)
    at com.intellij.execution.impl.EditConfigurationsDialog.access$001(EditConfigurationsDialog.java:33)
    at com.intellij.execution.impl.EditConfigurationsDialog$1.run(EditConfigurationsDialog.java:57)
    at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
    at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
    at com.intellij.execution.impl.EditConfigurationsDialog.show(EditConfigurationsDialog.java:54)
    at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:49)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:861)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:847)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.android.run.AvdComboBox PluginClassLoader[defrac.intellij, 0.0.18]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 100 more
```

**Comment by addicted2defrac** [comment]
Have you encountered this issue on a stable intellij version as well?

**Comment by mikeliucc** [comment]
Tried with IntelliJ 15.0.3, which is the latest official release at the time of this writing.  Indeed, the reported error is not observed for 15.0.3.   Any chance (timeline?) when we can use v16 with defrac?  16 is now in public preview now so API-wise it should be fairly stable.

Thanks for your consideration, Mike

**Comment by addicted2defrac** [comment]
when there is release candidate and this issue still pops up, we definitely going to fix it!
